### ISSUE TITLE
Send captured images to computer.

### ISSUE THREAD

**Issue by SureshbabuAkash1999** [Bloodevil/sony_camera_api#75]
Sir, could you also add a python program to send the captured images to computer via WIFI. Note:- I am using a raspberry pie, so the Sony play memories does not support in the same.

**Comment by mungewell** [comment]
I think it is unlikely that someone will just write some code for you, normal protocol is to at least try to implement something yourself... ;-)

The API documentation that this protocol implements is downloadable here:
https://developer.sony.com/develop/cameras/

The existing example scripts show how to discover/connect to the camera, in order to list/select/download the previously take photos and videos you would likely need to use the following calls.
```
getContentCount()
getContentList()
```

I have not tried, but I believe that the response will give a URI for downloading the desired image(s).
